In [12]:
%pylab inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import *
from sklearn.model_selection import train_test_split

Populating the interactive namespace from numpy and matplotlib


In [28]:
filename=r'https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data'
df=pd.read_csv(filename,index_col=None,header=None,na_values='?')
df=df.dropna()
df.head()


0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0

In [34]:
df

0    1    2      3      4    5    6      7    8    9    10   11   12  \
0    63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   
1    67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   
2    67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   
3    37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   
4    41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ...   
297  57.0  0.0  4.0  140.0  241.0  0.0  0.0  123.0  1.0  0.2  2.0  0.0  7.0   
298  45.0  1.0  1.0  110.0  264.0  0.0  0.0  132.0  0.0  1.2  2.0  0.0  7.0   
299  68.0  1.0  4.0  144.0  193.0  1.0  0.0  141.0  0.0  3.4  2.0  2.0  7.0   
300  57.0  1.0  4.0  130.0  131.0  0.0  0.0  115.0  1.0  1.2  2.0  1.0  7.0   
301  57.0  0.0  2.0  130.0  236.0  0.0  2.0  174.0  0.0  0.0  2.0  1.0  3.0   

     13  
0     0  
1     2  
2     1  
3     0  
4     0  
..   ..  
297   1  
298   1  
299   2  
300   3  
301   1  

[297 rows x 14 columns]

In [14]:
data=df.loc[:,0:12]
labels=1.0*(df.loc[:,13]>0)
print(data.shape,labels.shape)

(297, 13) (297,)


In [15]:
predicted_output=1.0*(data[0]>60)

In [16]:
print(confusion_matrix(labels,predicted_output))
#This is using only age(colume[0]) to predict the result. 

[[125  35]
 [ 93  44]]


In [17]:
print(confusion_matrix(labels,predicted_output).T)

[[125  93]
 [ 35  44]]


In [18]:
print(classification_report(labels,predicted_output))

              precision    recall  f1-score   support

         0.0       0.57      0.78      0.66       160
         1.0       0.56      0.32      0.41       137

    accuracy                           0.57       297
   macro avg       0.57      0.55      0.53       297
weighted avg       0.57      0.57      0.54       297



In [33]:
from sklearn.linear_model import LinearRegression
 
reg=LinearRegression().fit(data,labels)
predicted_output=reg.predict(data)>0.5
cm=confusion_matrix(labels,predicted_output)
print(cm)

[[144  16]
 [ 28 109]]
